### ISSUE TITLE
where is your blog website ? 

### ISSUE THREAD

**Issue by Iskindar** [Readm/Blog#9]
Brilliant! I am interested in the content of your blog. Is it free to share your website?

**Comment by Readm** [comment]
It will be [https://readm.readthedocs.io/zh_CN/latest/](), but I haven't started yet. :)
Feel free to share.
It will include:
+ Security thinking about CPU
+ Move some old blogs from readm.tech
+ Some other articles.

**Comment by Iskindar** [comment]
Thank you for your sharing! I will keep on it.
